# Utiliser Node.js
FROM node:20-alpine

# Définir le dossier de travail
WORKDIR /app

# Installer les dépendances
COPY package*.json ./
RUN npm install

# Copier le reste du projet
COPY . .

# Définir les permissions (sécurité)
RUN mkdir -p /app/node_modules && chown -R node:node /app

# Utilisateur non-root
USER node

# Lancer Next.js
CMD ["npm", "run", "dev"]
